### PR TITLE
add support for ipmitool/racadm passthru

### PR DESCRIPTION
**Pull request by nathangoulding**
## Description

Current PBNJ has a very limited set of operations that are explicitly allowed via endpoints. This PR expands the ability of PBNJ to include any command that a caller of PBNJ may want to run against a BMC using racadm or ipmitool. 

## Why is this needed
Fixes: #26 

## How Has This Been Tested?
Tests have been written to ensure backwards compatibility, in addition to tests of the new functionality.

## How are existing users impacted? What migration steps/scripts do we need?
None

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [x] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
Would it be better by using/working the stuff in the pbnj.next branch @nathangoulding ?

**Comment by nathangoulding** [comment]
@mmlb it seems like pbnj.next is still a ways out in terms of the proposal and implementation. Definitely a lot to uncover and figure out. Since this would be great to have for other microservices to leverage, can we merge this as-is?

**Comment by nathangoulding** [comment]
For the API that calls it, or build a new feature flag / toggle into PBNJ itself?

**Comment by jacobweinstock** [comment]
> For the API that calls it, or build a new feature flag / toggle into PBNJ itself?

yeah, sorry I was referencing a new feature flag/toggle built into PBnJ itself for this pass-thru functionality.

**Comment by jacobweinstock** [comment]
@nathangoulding, PBnJ.next has landed since we've lasted discussed this. Is this something you want to bring up for discussion again?

**Comment by nicklasfrahm** [comment]
Hey @nathangoulding, this issue has been stale for a while. Since PBnJ has a gRPC API now, this might need some extra work. We are closing this for now. If you want to continue this, we are mora than happy to reopen it.

**Comment by jacobweinstock** [comment]
closing with @nicklasfrahm's comment.

> Hey @nathangoulding, this issue has been stale for a while. Since PBnJ has a gRPC API now, this might need some extra work. We are closing this for now. If you want to continue this, we are mora than happy to reopen it.

**Pull request closed without merging**
