### PR TITLE
Added link to website

### PR DESCRIPTION
**Pull request by mrmrcoleman**
We're linking to the github repos directly in various marketing content, so we need to direct users back to the main site.

## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Hey @mrmrcoleman, thanks for this contribution! is it a duplicate of https://github.com/tinkerbell/pbnj/pull/53?

Also, looks like also you'll need to have the "Signed-off-by" line. if you're not familiar with this I usually just do that by adding a `-s` to my `git commit` command. 

https://probot.github.io/apps/dco/
https://github.com/tinkerbell/pbnj/pull/52/checks?check_run_id=1558341252

**Comment by mrmrcoleman** [comment]
@jacobweinstock This is it a duplicate of #53, thanks for catching that. I'll take a look at your comment above later on.

**Comment by jacobweinstock** [comment]
Hey @mrmrcoleman, looks like there has been a few changes to the README.md since you proposed this. Mind rebasing master?

Also, looks like you might need the DCO sign-off for the commit still.

**Comment by jacobweinstock** [comment]
@mrmrcoleman, please let me know if I can assist with this at all.

**Comment by nshalman** [comment]
Cleaned up into #89. Closing this one.

**Pull request closed without merging**
