### PR TITLE
Remove dependency on github.com/packethost/pkg/log/logr

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

The package `github.com/packethost/pkg/log/logr` is just a wrapper around https://github.com/go-logr/logr but makes updating dependencies difficult. This PR removes `github.com/packethost/pkg/log/logr` as a dependency.

## Why is this needed

Fixes: #

## How Has This Been Tested?

**Before this change:**
```bash
{
  "level": "info",
  "ts": 1644596496.81926,
  "caller": "grpc/server.go:129",
  "msg": "starting PBnJ gRPC server",
  "service": "github.com/tinkerbell/pbnj"
}
{
  "level": "info",
  "ts": 1644596515.628223,
  "caller": "rpc/machine.go:69",
  "msg": "start Power request",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "bmcIP": "localhost",
  "taskID": "c838q8qsahsseto0h94g",
  "username": "ADMIN",
  "vendor": "local",
  "powerAction": "POWER_ACTION_ON",
  "softTimeout": 0,
  "OffDuration": 0
}
{
  "level": "info",
  "ts": 1644596515.628288,
  "caller": "zap/options.go:203",
  "msg": "finished unary call with code OK",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "grpc.code": "OK",
  "grpc.time_ms": 0.20399999618530273
}
{
  "level": "info",
  "ts": 1644596515.648007,
  "caller": "machine/machine.go:276",
  "msg": "connected to BMC",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "bmcIP": "localhost",
  "taskID": "c838q8qsahsseto0h94g",
  "action": "POWER_ACTION_ON",
  "host": "localhost",
  "user": "ADMIN",
  "ProvidersAttempted": [
    "ipmitool",
    "*asrockrack.ASRockRack",
    "goipmi",
    "gofish",
    "idrac9"
  ],
  "SuccessfulOpenConns": [
    "ipmitool",
    "goipmi"
  ],
  "SuccessfulCloseConns": [],
  "SuccessfulProvider": ""
}
{
  "level": "info",
  "ts": 1644596515.700709,
  "caller": "machine/machine.go:337",
  "msg": "power POWER_ACTION_ON complete",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "bmcIP": "localhost",
  "taskID": "c838q8qsahsseto0h94g",
  "ProvidersAttempted": [
    "ipmitool"
  ],
  "SuccessfulOpenConns": [],
  "SuccessfulCloseConns": [],
  "SuccessfulProvider": "ipmitool"
}
{
  "level": "info",
  "ts": 1644596515.703198,
  "caller": "machine/machine.go:274",
  "msg": "closed connections",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "bmcIP": "localhost",
  "taskID": "c838q8qsahsseto0h94g",
  "ProvidersAttempted": [
    "ipmitool",
    "goipmi"
  ],
  "SuccessfulOpenConns": [],
  "SuccessfulCloseConns": [
    "ipmitool",
    "goipmi"
  ],
  "SuccessfulProvider": ""
}
{
  "level": "info",
  "ts": 1644596515.713459,
  "caller": "taskrunner/taskrunner.go:137",
  "msg": "task complete",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.start_time": "2022-02-11T09:21:55-07:00",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "grpc.method": "Power",
  "peer.address": "127.0.0.1:50153",
  "requestID": "P4SRi7Fn",
  "bmcIP": "localhost",
  "taskID": "c838q8qsahsseto0h94g",
  "description": "power action: POWER_ACTION_ON",
  "complete": true
}
```

**With this change:**
```bash
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/server.go:125",
  "time": 1644596424610,
  "message": "starting PBnJ gRPC server"
}
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.method": "Power",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "requestID": "fRwnGGMG",
  "bmcIP": "localhost",
  "taskID": "c838poasahssbubkancg",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "username": "ADMIN",
  "vendor": "local",
  "powerAction": "POWER_ACTION_ON",
  "softTimeout": 0,
  "OffDuration": 0,
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/rpc/machine.go:67",
  "time": 1644596449712,
  "message": "start Power request"
}
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.method": "Power",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "requestID": "fRwnGGMG",
  "bmcIP": "localhost",
  "taskID": "c838poasahssbubkancg",
  "action": "POWER_ACTION_ON",
  "host": "localhost",
  "user": "ADMIN",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "ProvidersAttempted": [
    "ipmitool",
    "*asrockrack.ASRockRack",
    "gofish",
    "idrac9"
  ],
  "SuccessfulOpenConns": [
    "ipmitool"
  ],
  "SuccessfulCloseConns": [],
  "SuccessfulProvider": "",
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/oob/machine/machine.go:276",
  "time": 1644596449728,
  "message": "connected to BMC"
}
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.method": "Power",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "requestID": "fRwnGGMG",
  "bmcIP": "localhost",
  "taskID": "c838poasahssbubkancg",
  "ProvidersAttempted": [
    "ipmitool"
  ],
  "SuccessfulOpenConns": [],
  "SuccessfulCloseConns": [],
  "SuccessfulProvider": "ipmitool",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/oob/machine/machine.go:337",
  "time": 1644596449905,
  "message": "power POWER_ACTION_ON complete"
}
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.method": "Power",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "requestID": "fRwnGGMG",
  "bmcIP": "localhost",
  "taskID": "c838poasahssbubkancg",
  "ProvidersAttempted": [
    "ipmitool"
  ],
  "SuccessfulOpenConns": [],
  "SuccessfulCloseConns": [
    "ipmitool"
  ],
  "SuccessfulProvider": "",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/oob/machine/machine.go:274",
  "time": 1644596449915,
  "message": "closed connections"
}
{
  "level": "info",
  "service": "github.com/tinkerbell/pbnj",
  "grpc.method": "Power",
  "grpc.service": "github.com.tinkerbell.pbnj.api.v1.Machine",
  "requestID": "fRwnGGMG",
  "bmcIP": "localhost",
  "taskID": "c838poasahssbubkancg",
  "description": "power action: POWER_ACTION_ON",
  "v": 0,
  "logger": "github.com/tinkerbell/pbnj",
  "complete": true,
  "caller": "/Users/jacobweinstock/repos/tinkerbell/pbnj/grpc/taskrunner/taskrunner.go:135",
  "time": 1644596449926,
  "message": "task complete"
}
```

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by abhay-krishna** [comment]
This is great! Thanks for doing this @jacobweinstock !

**Comment by abhay-krishna** [comment]
@jacobweinstock This looks good. Glad you bumped `github.com/manifoldco/promptui` to `v0.9.0` since `v0.8.0` of promptui was pulling in `github.com/juju/ansiterm`, an LGPL dependency.

**Comment by jacobweinstock** [comment]
> @jacobweinstock This looks good. Glad you bumped `github.com/manifoldco/promptui` to `v0.9.0` since `v0.8.0` of promptui was pulling in `github.com/juju/ansiterm`, an LGPL dependency. Are there any breaking changes involved in this removal? I'm not familiar with the codebase, but as far as I reviewed, I observed that the packethost logr was being replaced with go-logr/logr and zerologr, and other methods fixed to use these new logging constructs.

Hey @abhay-krishna, from the protobuf API's perspective ([here](https://github.com/tinkerbell/pbnj/tree/main/api/v1)) there are no breaking changes. This change affects what the logs will look like. They'll be a little different than before.

**Comment by abhay-krishna** [comment]
@jacobweinstock That makes sense, thanks for clarifying. Any idea when this will be merged?

**Comment by nshalman** [comment]
> This change affects what the logs will look like. They'll be a little different than before.

Can you add some examples of before and after to the testing section?

**Review by nshalman — DISMISSED** [review]
LGTM

**Comment by jacobweinstock** [comment]
Hey @nshalman, sorry your approval got dismissed when I rebased main. whenever you have a moment, please and thank you!

**Review by nshalman — APPROVED** [review]

**Comment by abhay-krishna** [comment]
@jacobweinstock Thanks for merging this!! 🎉

**Pull request merged**
