### PR TITLE
Replace Drone badge with GitHub Action

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
These drone CI banners are no longer used

### CODE REVIEW

**Comment by mmlb** [comment]
Is there a github actions alternative?

**Comment by markyjackson-taulia** [comment]
> Is there a github actions alternative?

No, this will need to be built out

**Comment by jacobweinstock** [comment]
is this something we could update to GitHub actions with something like this? 
```text
![For each commit and PR](https://github.com/tinkerbell/pbnj/workflows/For%20each%20commit%20and%20PR/badge.svg)
```
For each commit and PR

**Review by jacobweinstock — APPROVED** [review]

**Comment by mmlb** [comment]
That works for me, @jacobweinstock thanks for the pointer.

**Review by jacobweinstock — APPROVED** [review]

**Comment by mmlb** [comment]
took myself off the review list

**Comment by jacobweinstock** [comment]
@mmlb thanks for fixing the build too!!

**Review by jacobweinstock — APPROVED** [review]

**Pull request merged**
